# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Lint with flake8
      uses: py-actions/flake8@v2
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        ./tests.sh
